### ISSUE TITLE
Unit test improvements

### ISSUE THREAD

**Issue by JWCook** [lsaffre/sphinxfeed#6]
Following up from #2 and #5. Here are some changes I would like to make to the unit tests:

* Improve test coverage:
  * Test both rst and markdown input
  * Test both RSS and Atom output
* Get tests fully working in CI:
  * Currently, tests compare the full build output, which changes slightly when dependency versions change (Sphinx, docutils, etc.). This could be improved by checking only the main feed contents and ignoring minor variations like formatting, whitespace, `lastBuildDate`, etc.
  * It looks like the tests are also checking HTML output. Do you think we could skip that and only check the feed XML output?

**Comment by lsaffre** [comment]
Yes, we should optimize the tests for better maintainability. The current implementation was quickly made and it it did work for me until now, but it definitively can be improved. For example get rid of the versions dependency by skipping the details of the html output, and increase coverage.
